*************************** 1. row ***************************
                id: 1425
              name: lapo
            symbol: LAX
           symbol2: NULL
              algo: lyra2zz
           version: 4
             image: NULL
            market: NULL
          marketid: NULL
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 1
         sellonbid: NULL
          dontsell: 1
    block_explorer: http://explorer.lapo.io/
         index_avg: NULL
       connections: 0
            errors: NULL
           balance: NULL
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: NULL
             txfee: 1
        payout_min: 1
        payout_max: 10
        block_time: NULL
        difficulty: 1
    difficulty_pos: NULL
      block_height: NULL
     target_height: NULL
     powend_height: NULL
      network_hash: NULL
             price: NULL
            price2: NULL
            reward: 1
        reward_mul: 1
     mature_blocks: NULL
            enable: 1
        auto_ready: 1
           visible: NULL
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: NULL
           program: NULL
           rpcuser: rpcuser
         rpcpasswd: password1
        serveruser: NULL
           rpchost: 127.0.0.1
           rpcport: 31718
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POW
           account: 
        hasgetinfo: 1
    hassubmitblock: 1
    hasmasternodes: 1
     usememorypool: NULL
         usesegwit: 0
         txmessage: NULL
            auxpow: NULL
        multialgos: 0
         lastblock: NULL
       network_ttf: NULL
        actual_ttf: NULL
          pool_ttf: NULL
last_network_found: NULL
         installed: NULL
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: NULL
       link_github: NULL
     link_explorer: NULL
    specifications: NULL
