*************************** 1. row ***************************
                id: 6
              name: Bitcoin
            symbol: BTC
           symbol2: 
              algo: sha256
           version: 109900
             image: /images/coin-6.png
            market: 
          marketid: 0
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 0.005
         sellonbid: 0
          dontsell: 1
    block_explorer: 
         index_avg: 0.0000049361618444422
       connections: 0
            errors: This is a pre-release test build - use at your own risk - do not use for mining or merchant applications
           balance: 0
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: 0
             txfee: 0
        payout_min: NULL
        payout_max: NULL
        block_time: NULL
        difficulty: 51076366303.482
    difficulty_pos: NULL
      block_height: 364900
     target_height: 349481
     powend_height: NULL
      network_hash: 80.81
             price: 1
            price2: 1
            reward: 25.21212105
        reward_mul: 1
     mature_blocks: NULL
            enable: 0
        auto_ready: 0
           visible: 0
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: 
           program: 
           rpcuser: NULL
         rpcpasswd: NULL
        serveruser: NULL
           rpchost: yaamp1
           rpcport: 10301
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POW
           account: 
        hasgetinfo: 1
    hassubmitblock: 1
    hasmasternodes: 0
     usememorypool: NULL
         usesegwit: 0
         txmessage: 1
            auxpow: 0
        multialgos: 0
         lastblock: 00000000000000000da2a64a9a8e32623575ba19c3125077d1715c1ba2d3b90c
       network_ttf: 2147483647
        actual_ttf: 596
          pool_ttf: 2147483647
last_network_found: 1436648004
         installed: 1
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: NULL
       link_github: NULL
     link_explorer: NULL
    specifications: NULL
*************************** 2. row ***************************
                id: 77
              name: UroCoin
            symbol: URO
           symbol2: 
              algo: x11
           version: 1000204
             image: /images/coin-77.png
            market: bittrex
          marketid: NULL
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 1
         sellonbid: 0
          dontsell: 1
    block_explorer: 
         index_avg: 0.11906304821704
       connections: 0
            errors: 
           balance: 0
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: 0
             txfee: 0
        payout_min: NULL
        payout_max: NULL
        block_time: NULL
        difficulty: 22.464980818286
    difficulty_pos: NULL
      block_height: 198891
     target_height: NULL
     powend_height: NULL
      network_hash: 2027335785
             price: 0.00044579151572707
            price2: 0.00045867861107593
            reward: 0.6
        reward_mul: 1
     mature_blocks: NULL
            enable: 0
        auto_ready: 1
           visible: 1
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: .Uro
           program: Urod
           rpcuser: NULL
         rpcpasswd: NULL
        serveruser: NULL
           rpchost: yaamp2
           rpcport: 7700
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POW
           account: 
        hasgetinfo: 1
    hassubmitblock: 1
    hasmasternodes: 0
     usememorypool: NULL
         usesegwit: 0
         txmessage: 1
            auxpow: 0
        multialgos: 0
         lastblock: 0000000000cb3c30a62d81fbb5d3c8b677fcf850424626289de485ef278bab2d
       network_ttf: 47
        actual_ttf: 187
          pool_ttf: 54592
last_network_found: 1436648004
         installed: 1
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: https://bitcointalk.org/index.php?topic=600639.0
       link_github: https://github.com/urocoin/uro
     link_explorer: 
    specifications: NULL
*************************** 3. row ***************************
                id: 104
              name: CannabisCoin
            symbol: CANN
           symbol2: 
              algo: x11
           version: 80603
             image: /images/coin-104.png
            market: cryptsy
          marketid: 300
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 1
         sellonbid: 0
          dontsell: 1
    block_explorer: 
         index_avg: 0.049772594392464
       connections: 0
            errors: 
           balance: 0
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: 0
             txfee: 0
        payout_min: NULL
        payout_max: NULL
        block_time: NULL
        difficulty: 10.058901402506
    difficulty_pos: NULL
      block_height: 768149
     target_height: NULL
     powend_height: NULL
      network_hash: 9603692753
             price: 0.000018667824026608
            price2: 0.000019239584365976
            reward: 3.28125
        reward_mul: 1
     mature_blocks: NULL
            enable: 0
        auto_ready: 0
           visible: 1
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: 
           program: 
           rpcuser: NULL
         rpcpasswd: NULL
        serveruser: NULL
           rpchost: yaamp2
           rpcport: 1040
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POW
           account: 
        hasgetinfo: 1
    hassubmitblock: 1
    hasmasternodes: 0
     usememorypool: NULL
         usesegwit: 0
         txmessage: 1
            auxpow: 0
        multialgos: 0
         lastblock: 0000000013d1d83820efe250d85e9981f071544be6c77f13046e14d8930b19b2
       network_ttf: 4
        actual_ttf: 42
          pool_ttf: 5
last_network_found: 1434809263
         installed: 0
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: NULL
       link_github: NULL
     link_explorer: NULL
    specifications: NULL
*************************** 4. row ***************************
                id: 142
              name: Potcoin
            symbol: POT
           symbol2: 
              algo: scrypt
           version: 80604
             image: /images/coin-POT.png
            market: cryptsy
          marketid: 173
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 1
         sellonbid: 0
          dontsell: 1
    block_explorer: 
         index_avg: 0.15901476683261
       connections: 0
            errors: 
           balance: 0
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: 0
             txfee: 0
        payout_min: NULL
        payout_max: NULL
        block_time: NULL
        difficulty: 19.64510621755
    difficulty_pos: NULL
      block_height: 852263
     target_height: NULL
     powend_height: NULL
      network_hash: 7268462171
             price: 0.0000047334000002007
            price2: 0.0000048499920774144
            reward: 52.5
        reward_mul: 1
     mature_blocks: NULL
            enable: 0
        auto_ready: 0
           visible: 0
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: .potcoin
           program: potcoind
           rpcuser: NULL
         rpcpasswd: NULL
        serveruser: NULL
           rpchost: yaamp3
           rpcport: 1420
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POW
           account: 
        hasgetinfo: 1
    hassubmitblock: 1
    hasmasternodes: 0
     usememorypool: NULL
         usesegwit: 0
         txmessage: 1
            auxpow: 0
        multialgos: 0
         lastblock: afcac989737f234d3750de45e09d6a9dae2dce32e8df309cb1f37ee7ded9fbf2
       network_ttf: 11
        actual_ttf: 68
          pool_ttf: 77
last_network_found: 1434809095
         installed: 0
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: NULL
       link_github: NULL
     link_explorer: NULL
    specifications: NULL
*************************** 5. row ***************************
                id: 145
              name: Tagcoin
            symbol: TAG
           symbol2: 
              algo: scrypt
           version: v1.1.0
             image: /images/coin-145.png
            market: cryptsy
          marketid: 117
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 1
         sellonbid: 0
          dontsell: 1
    block_explorer: 
         index_avg: 0.12220784834201
       connections: 0
            errors: 
           balance: 0
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: 0
             txfee: 0.001
        payout_min: NULL
        payout_max: NULL
        block_time: NULL
        difficulty: 630.82394688914
    difficulty_pos: NULL
      block_height: 212977
     target_height: NULL
     powend_height: NULL
      network_hash: NULL
             price: 0
            price2: 0
            reward: 28.054995
        reward_mul: 100
     mature_blocks: NULL
            enable: 0
        auto_ready: 0
           visible: 1
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: .TagCoin
           program: tagcoind
           rpcuser: NULL
         rpcpasswd: NULL
        serveruser: NULL
           rpchost: yaamp2
           rpcport: 1450
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POS
           account: 
        hasgetinfo: 1
    hassubmitblock: 1
    hasmasternodes: 0
     usememorypool: NULL
         usesegwit: 0
         txmessage: 1
            auxpow: 0
        multialgos: 0
         lastblock: 00000000006cdf26ffe113390f4df25ebf7dfb3cf8e5981647b45602df734b9a
       network_ttf: NULL
        actual_ttf: 213
          pool_ttf: 1614
last_network_found: 1434809095
         installed: 0
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: https://bitcointalk.org/index.php?topic=317408.0
       link_github: https://github.com/tagcoin/tagcoin.git
     link_explorer: 
    specifications: NULL
*************************** 6. row ***************************
                id: 146
              name: Dogecoin
            symbol: DOGE
           symbol2: 
              algo: scrypt
           version: 1080200
             image: /images/coin-DOGE.png
            market: cryptsy
          marketid: 132
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 1
         sellonbid: 0
          dontsell: 1
    block_explorer: 
         index_avg: 0.0047783768459481
       connections: 0
            errors: 
           balance: 0
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: 0
             txfee: 0
        payout_min: NULL
        payout_max: NULL
        block_time: NULL
        difficulty: 16287.075312856
    difficulty_pos: NULL
      block_height: 757676
     target_height: 278106
     powend_height: NULL
      network_hash: 1393789598124
             price: 0.00000068600000019942
            price2: 0.00000070500000020414
            reward: 10010.005
        reward_mul: 1
     mature_blocks: NULL
            enable: 0
        auto_ready: 0
           visible: 1
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: .dogecoin
           program: dogecoind
           rpcuser: NULL
         rpcpasswd: NULL
        serveruser: NULL
           rpchost: yaamp2
           rpcport: 1460
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POW
           account: 
        hasgetinfo: 1
    hassubmitblock: 1
    hasmasternodes: 0
     usememorypool: NULL
         usesegwit: 0
         txmessage: 1
            auxpow: 1
        multialgos: 0
         lastblock: db758562008edaab7f6a9bcdb8b1289ea77e6013c156e491ae79a8efd5374ced
       network_ttf: 50
        actual_ttf: 64
          pool_ttf: 36094
last_network_found: 1434809263
         installed: 0
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: NULL
       link_github: NULL
     link_explorer: NULL
    specifications: NULL
*************************** 7. row ***************************
                id: 153
              name: Rubycoin
            symbol: RBY
           symbol2: NULL
              algo: scrypt
           version: 80602
             image: NULL
            market: bittrex
          marketid: NULL
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 1
         sellonbid: 0
          dontsell: 1
    block_explorer: 
         index_avg: 0.11496466133736
       connections: 0
            errors: 
           balance: 0
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: 0
             txfee: 0
        payout_min: NULL
        payout_max: NULL
        block_time: NULL
        difficulty: 11.09036451
    difficulty_pos: NULL
      block_height: 136036
     target_height: NULL
     powend_height: NULL
      network_hash: 852814807
             price: 0.0000051
            price2: NULL
            reward: 25
        reward_mul: 1
     mature_blocks: NULL
            enable: 0
        auto_ready: 0
           visible: 1
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: .rubycoin
           program: rubycoind
           rpcuser: NULL
         rpcpasswd: NULL
        serveruser: NULL
           rpchost: yaamp2
           rpcport: 10546
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POW
           account: 
        hasgetinfo: 1
    hassubmitblock: 1
    hasmasternodes: 0
     usememorypool: NULL
         usesegwit: 0
         txmessage: 1
            auxpow: NULL
        multialgos: 0
         lastblock: 746633ca8ad79093d38049bd431de6371707c3a571b2a9aecd53813c22e5d347
       network_ttf: 55
        actual_ttf: 437
          pool_ttf: 32
last_network_found: 1414658859
         installed: 0
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: https://bitcointalk.org/index.php?topic=459622.0
       link_github: https://github.com/rubycoinorg/rubycoin.git
     link_explorer: 
    specifications: NULL
*************************** 8. row ***************************
                id: 154
              name: Dnotes
            symbol: NOTE
           symbol2: NULL
              algo: scrypt
           version: 1010000
             image: NULL
            market: c-cex
          marketid: NULL
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 1
         sellonbid: 0
          dontsell: 1
    block_explorer: 
         index_avg: 0.12399596331488
       connections: 0
            errors: 
           balance: 0
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: 0
             txfee: 0
        payout_min: NULL
        payout_max: NULL
        block_time: NULL
        difficulty: 24.85030091
    difficulty_pos: NULL
      block_height: 387865
     target_height: 257053
     powend_height: NULL
      network_hash: 1772944014
             price: 0.000012325348
            price2: NULL
            reward: 25
        reward_mul: 1
     mature_blocks: NULL
            enable: 0
        auto_ready: 0
           visible: 1
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: .DNotes
           program: DNotesd
           rpcuser: NULL
         rpcpasswd: NULL
        serveruser: NULL
           rpchost: yaamp2
           rpcport: 10548
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POW
           account: 
        hasgetinfo: 1
    hassubmitblock: 0
    hasmasternodes: 0
     usememorypool: NULL
         usesegwit: 0
         txmessage: 1
            auxpow: NULL
        multialgos: 0
         lastblock: 2cfbe8a5ac612884ea725fb8b55ec979dd0d7ab23c83fae3a66327252b5f7048
       network_ttf: 60
        actual_ttf: 62
          pool_ttf: 72
last_network_found: 1415970638
         installed: 0
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: NULL
       link_github: NULL
     link_explorer: NULL
    specifications: NULL
*************************** 9. row ***************************
                id: 155
              name: Litecoin
            symbol: LTC
           symbol2: 
              algo: scrypt
           version: 100202
             image: /images/coin-LTC.png
            market: cryptsy
          marketid: 3
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 1
         sellonbid: 0
          dontsell: 1
    block_explorer: 
         index_avg: 0.15171290682319
       connections: 0
            errors: 
           balance: 0
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: 0
             txfee: 0
        payout_min: NULL
        payout_max: NULL
        block_time: NULL
        difficulty: 37795.256432821
    difficulty_pos: NULL
      block_height: 801487
     target_height: 623311
     powend_height: NULL
      network_hash: 1601025169698
             price: 0.020277576824097
            price2: 0.020814137099131
            reward: 50.004
        reward_mul: 1
     mature_blocks: NULL
            enable: 0
        auto_ready: 0
           visible: 0
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: .litecoin
           program: litecoind
           rpcuser: NULL
         rpcpasswd: NULL
        serveruser: NULL
           rpchost: yaamp2
           rpcport: 1550
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POW
           account: 
        hasgetinfo: 1
    hassubmitblock: 1
    hasmasternodes: 0
     usememorypool: NULL
         usesegwit: 0
         txmessage: 1
            auxpow: 0
        multialgos: 0
         lastblock: 3cc70477beb50adcebc1970295bc9ded2aaae9f4506df3f59f13b1919b0653b0
       network_ttf: 101
        actual_ttf: 128
          pool_ttf: 95328
last_network_found: 1434809263
         installed: 0
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: NULL
       link_github: NULL
     link_explorer: NULL
    specifications: NULL
*************************** 10. row ***************************
                id: 187
              name: Novacoin
            symbol: NVC
           symbol2: NULL
              algo: scrypt
           version: v0.4.4.6-nvc-update2-90-g45802ef
             image: NULL
            market: cryptsy
          marketid: 13
     master_wallet: NULL
   charity_address: NULL
    charity_amount: NULL
   charity_percent: NULL
   deposit_address: NULL
   deposit_minimum: 1
         sellonbid: 0
          dontsell: 1
    block_explorer: 
         index_avg: 0
       connections: 0
            errors: 
           balance: 0
          immature: NULL
           cleared: NULL
         available: NULL
             stake: NULL
              mint: 0
             txfee: 0.001
        payout_min: NULL
        payout_max: NULL
        block_time: NULL
        difficulty: 1768.8680180112
    difficulty_pos: 0.89812112
      block_height: 155248
     target_height: 121559
     powend_height: NULL
      network_hash: NULL
             price: 0.0023334279
            price2: NULL
            reward: 7.19
        reward_mul: 100
     mature_blocks: NULL
            enable: 0
        auto_ready: 0
           visible: 1
       no_explorer: 0
        max_miners: NULL
        max_shares: NULL
           created: NULL
            action: NULL
       conf_folder: .novacoin
           program: novacoind
           rpcuser: NULL
         rpcpasswd: NULL
        serveruser: NULL
           rpchost: yaamp2
           rpcport: 10614
           rpccurl: 0
            rpcssl: 0
           rpccert: NULL
       rpcencoding: POS
           account: 
        hasgetinfo: 1
    hassubmitblock: 1
    hasmasternodes: 0
     usememorypool: NULL
         usesegwit: 0
         txmessage: 1
            auxpow: 0
        multialgos: 0
         lastblock: 0000000000084bec3b22dfba21eb1e064e44dfd8b3ec375e091af8199487a06c
       network_ttf: NULL
        actual_ttf: 394
          pool_ttf: 6863
last_network_found: 1423315998
         installed: 0
             watch: 0
         link_site: NULL
     link_exchange: NULL
  link_bitcointalk: NULL
       link_github: NULL
     link_explorer: NULL
    specifications: NULL
